### PR TITLE
fix: fix soundness issue related to storing a reference in `Ref` and `RefMut`.

### LINKED ISSUE #2: Ref/RefMut types cannot hold plain references
See https://github.com/bholley/atomic_refcell/pull/18

### PR DESCRIPTION
**Pull request by zicklag**
Fixes: #2

Adds a test that fails miri before this PR, and passes after it.

### CODE REVIEW

File: src/refs/immutable.rs [hunk 1]
```diff
@@ -145,7 +147,8 @@ where
     #[inline]
     pub fn new(r: &'a T) -> Self {
         Ref {
-            value: r,
+            // SAFETY: An `&T` reference cannot be null
+            value: unsafe { NonNull::new_unchecked(r as *const T as *mut T) },
```
Comment (Imberflur) [inline src/refs/immutable.rs]: `NonNull` implements  `From<&T>` and `From<&mut T>`, so this can just be a safe `NonNull::from(r)`

This note applies to all lines using `NonNull::new_unchecked`

File: src/refs/mutable.rs [hunk 2]
```diff
@@ -19,7 +20,7 @@ use crate::borrow::AtomicBorrowMut;
 /// [`AtomicCell`]: struct.AtomicCell.html
 /// [`&T`]: https://doc.rust-lang.org/core/primitive.reference.html
 pub struct RefMut<'a, T: ?Sized> {
-    value: &'a mut T,
+    value: NonNull<T>,
```
Comment (Imberflur) [inline src/refs/mutable.rs:24]: `NonNull<T>` is covariant over `T` but `RefMut` allows mutable access so it needs to be invariant over `T` to be sound, to accomplish this a `PhamtomData<&'a mut T>` field can be included. https://doc.rust-lang.org/reference/subtyping.html#variance

File: src/refs/immutable.rs [hunk 3]
```diff
@@ -19,7 +20,7 @@ use crate::borrow::AtomicBorrow;
 /// [`AtomicCell`]: struct.AtomicCell.html
 /// [`&T`]: https://doc.rust-lang.org/core/primitive.reference.html
 pub struct Ref<'a, T: ?Sized> {
-    value: &'a T,
+    value: NonNull<T>,
```
Comment (Imberflur) [inline src/refs/immutable.rs:23]: `NonNull` is not `Send`/`Sync` so you will probably want to manually implement this on `Ref`/`RefMut` (assuming that `AtomicBorrow` is `Send`/`Sync`), see my PR on `atomic_refcell` for reference.

**Comment by zicklag** [comment]
Thank you very much @Imberflur for the review! I updated the PR accordingly.

File: src/refs/immutable.rs [hunk 4]
```diff
@@ -201,7 +211,7 @@ where
     /// }
     /// ```
     #[inline]
-    pub unsafe fn into_split(r: Ref<'a, T>) -> (&'a T, AtomicBorrow<'a>) {
+    pub unsafe fn into_split(r: Ref<'a, T>) -> (NonNull<T>, AtomicBorrow<'a>) {
         (r.value, r.borrow)
     }
```
Comment (Imberflur) [inline src/refs/immutable.rs]: This function can be safe now since it is unsafe to read from the `NonNull<T>`

File: src/refs/mutable.rs [hunk 5]
```diff
@@ -19,10 +21,17 @@ use crate::borrow::AtomicBorrowMut;
...
     borrow: AtomicBorrowMut<'a>,
+    /// This forces [`RefMut`] to be invariant over T, which is required to be sound because it may
+    /// modify T.
+    _phantom: PhantomData<&'a mut T>,
 }
 
+// SAFETY: `Ref<'_, T> acts as a reference. `AtomicBorrowR` is a reference to an atomic.
+unsafe impl<'b, T: ?Sized + 'b> Sync for RefMut<'b, T> where for<'a> &'a T: Sync {}
+unsafe impl<'b, T: ?Sized + 'b> Send for RefMut<'b, T> where for<'a> &'a T: Send {}
```
Comment (Imberflur) [inline src/refs/mutable.rs]: `&'a T -> &'a mut T` for both of these

**Review by Imberflur — COMMENTED** [review]
Here are a couple more things I noticed when scanning the new diff

File: src/refs/immutable.rs (hunk 4 above)
Comment (Imberflur) [reply src/refs/immutable.rs]: oh and I assume there is a similar situation for `RefMut`, also users of that case might need to be careful since `NonNull<T>` is covariant over `T`

Comment (zicklag) [reply src/refs/immutable.rs]: I think it makes sense to leave these `unsafe` because of the extra soundness invariants associated with it that are not documented with `NonNull<T>`, i.e. that it is only valid to dereference the `NonNull` if the atomic guard has not been dropped.

---

Good point with the `NonNull` being covariant. As an experiment, I tested out a `NonNullMut<T>` wrapper type that is invariant over `T`, which seems useful in this context. This allows the user to store the `NonNullMut<T>` in whatever guard type they want along with the `AtomicBorrow`, without having to also add and phantom data to make it invariant.

Do you think there are any problems with that approach?

Comment (Imberflur) [reply src/refs/immutable.rs]: I don't see any particular issues with that other than just the implicit complexity overhead of introducing a new type to work with. 

Ideally, if `MaybeDangling<T>` existed in `std`, then `MaybeDangling<&'a mut T>` might work well.

----

> I think it makes sense to leave these unsafe because of the extra soundness invariants associated with it that are not documented with `NonNull<T>`

The thing is, a `NonNull` considered by itself doesn't give any guarantee that it is ever valid to dereference. The user dereferencing a `NonNull` must always be aware of its origins to ensure proper alignment, that it is pointing to a valid allocation with a valid instance of `T`, there are no aliasing conflicts, the pointer has the correct provenance for the access being performed, etc. So rather than the API here applying additional invariants that must be met to soundly deference the `NonNull`, instead it is providing the guarantee that the `NonNull` will meet all these existing requirements if the atomic guard has not been dropped.

Comment (zicklag) [reply src/refs/immutable.rs]: > So rather than the API here applying additional invariants that must be met to soundly deference the NonNull, instead it is providing the guarantee that the NonNull will meet all these existing requirements if the atomic guard has not been dropped.

Ah, yeah, that perspective makes sense to me. 👍️ Updated it to be safe.

---

Regarding the `NonNullMut` wrapper, I'm really on the fence whether or not to document the extra invariant, keep the wrapper type, or use the [`maybe-dangling`](https://docs.rs/maybe-dangling/latest/maybe_dangling/struct.MaybeDangling.html) crate.

@zakarumych do you have an opinion on this?

Comment (zakarumych) [reply src/refs/immutable.rs]: I would keep simple `NonNull` and add `PhantomData<&mut T>` to `RefMut` to make it invariant over `T`.

**Comment by zicklag** [comment]
I removed the `NonNullMut` wrapper and added an extra safety comment to `RefMut::into_split`.

**Comment by zakarumych** [comment]
Looks great! Thank you!
